import 'bootstrap/dist/css/bootstrap.css';
import { Montserrat, Open_Sans } from "next/font/google";
import "@/css/globals.scss";
import BootstrapClient from '@/components/BootstrapClient';
import Header from '@/components/Header';
import Footer from '@/components/Footer';

const montserrat = Montserrat({ subsets: ["latin"], variable: '--font-montserrat' });
const openSans = Open_Sans({ subsets: ["latin"], variable: '--font-open-sans' });

export const metadata = {
  title: "Isotech",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${montserrat.variable} ${openSans.variable}`}>
        <Header />

        <main>
            {children}
        </main>

        <BootstrapClient />

        <Footer />
    </body>
    </html>
  );
}
